### ISSUE TITLE
[move] Fix the Move IDE integration

### ISSUE THREAD

**Issue by miker83z** [iotaledger/iota#1246]
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/iota/issues/1828
- [ ] https://github.com/iotaledger/iota/issues/1829
- [ ] https://github.com/iotaledger/iota/issues/1830
- [ ] https://github.com/iotaledger/iota/issues/1831
- [ ] https://github.com/iotaledger/iota/issues/1832
- [ ] https://github.com/iotaledger/iota/issues/3709
- [ ] https://github.com/iotaledger/iota/issues/3710
- [ ] https://github.com/iotaledger/iota/issues/3816
- [ ] https://github.com/iotaledger/iota/issues/3818
- [ ] https://github.com/iotaledger/iota/issues/3821
- [ ] https://github.com/iotaledger/iota/issues/3822
- [ ] https://github.com/iotaledger/iota/issues/4241
- [ ] https://github.com/iotaledger/iota/issues/4292
```
