### ISSUE TITLE
[CI]: Taskforce Mandate

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota#1359]
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/iota/issues/4202
- [ ] https://github.com/iotaledger/iota/issues/2243
- [ ] https://github.com/iotaledger/iota/issues/1366
- [ ] https://github.com/iotaledger/iota/issues/3506
- [ ] https://github.com/iotaledger/iota/issues/1371
- [ ] https://github.com/iotaledger/iota/issues/2137
- [ ] https://github.com/iotaledger/iota/issues/2887
- [ ] https://github.com/iotaledger/iota/issues/1364
- [ ] https://github.com/iotaledger/iota/issues/1382
- [ ] https://github.com/iotaledger/iota/issues/1361
- [ ] https://github.com/iotaledger/iota/issues/1971
- [ ] https://github.com/iotaledger/iota/issues/2042
- [ ] https://github.com/iotaledger/iota/issues/612
- [ ] https://github.com/iotaledger/iota/issues/2051
- [ ] https://github.com/iotaledger/iota/issues/1362
- [ ] https://github.com/iotaledger/iota/issues/1629
- [ ] https://github.com/iotaledger/iota/issues/1664
- [ ] https://github.com/iotaledger/iota/issues/1363
- [ ] https://github.com/iotaledger/iota/issues/1368
- [ ] https://github.com/iotaledger/iota/issues/1365
- [ ] https://github.com/iotaledger/iota/issues/1665
- [ ] https://github.com/iotaledger/iota/issues/1370
- [ ] https://github.com/iotaledger/iota/issues/1511
- [ ] https://github.com/iotaledger/iota/issues/1367
- [ ] https://github.com/iotaledger/iota/issues/1369
- [ ] https://github.com/iotaledger/iota/issues/1360
- [ ] https://github.com/iotaledger/iota/issues/1472
```
