### ISSUE TITLE
Review and verify documentation functionality

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/iota#1409]
Since most of our documentation has been imported, and we're already aware of outdated code examples, please go through all the docs and user-test them to ensure everything still holds. If it's not and it's something small, please create a PR directly; if it's something that will require more substantial efforts, please create an issue to follow up.

**The L1SC team is working on a similar [epic](https://github.com/iotaledger/iota/issues/1245). We should wait till they go through each section before starting work on the same. **

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/iota/issues/1412
- [ ] https://github.com/iotaledger/iota/issues/1410
- [ ] https://github.com/iotaledger/iota/issues/1411
- [ ] https://github.com/iotaledger/iota/issues/1419
- [ ] https://github.com/iotaledger/iota/issues/1413
- [ ] https://github.com/iotaledger/iota/issues/1420
- [ ] https://github.com/iotaledger/iota/issues/1414
- [ ] https://github.com/iotaledger/iota/issues/1415
- [ ] https://github.com/iotaledger/iota/issues/1416
- [ ] https://github.com/iotaledger/iota/issues/1417
- [ ] https://github.com/iotaledger/iota/issues/1418
- [ ] https://github.com/iotaledger/iota/issues/1492
```
