### ISSUE TITLE
DevEx - IOTA Rebased Docs

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/iota#1429]
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/361
- [ ] https://github.com/iotaledger/devx/issues/362
- [ ] https://github.com/iotaledger/iota/issues/4047
- [ ] https://github.com/iotaledger/devx/issues/365
- [ ] https://github.com/iotaledger/devx/issues/425
- [ ] https://github.com/iotaledger/devx/issues/437
- [ ] https://github.com/iotaledger/iota/issues/1421
- [ ] https://github.com/iotaledger/iota/issues/1423
- [ ] https://github.com/iotaledger/iota/issues/1424
- [ ] https://github.com/iotaledger/iota/issues/1425
- [ ] https://github.com/iotaledger/iota/issues/1426
- [ ] https://github.com/iotaledger/iota/issues/1409
- [ ] https://github.com/iotaledger/devx/issues/463
- [ ] https://github.com/iotaledger/iota/issues/1427
- [ ] https://github.com/iotaledger/devx/issues/472
- [ ] https://github.com/iotaledger/iota/issues/1428
- [ ] https://github.com/iotaledger/iota/issues/1387
```
