### ISSUE TITLE
Automate documentation generation

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/iota#1437]
One of the major pitfalls that can occur in the documentation process is for references and other guides to fall out of date. To avoid this, we should:

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/iota/issues/1432
- [ ] https://github.com/iotaledger/iota/issues/1433
- [ ] https://github.com/iotaledger/iota/issues/1434
- [ ] https://github.com/iotaledger/iota/issues/1435
```
