### ISSUE TITLE
Required docs software tasks

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/iota#1445]
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/iota/issues/1431
- [ ] https://github.com/iotaledger/devx/issues/357
- [ ] https://github.com/iotaledger/iota/issues/1437
- [ ] https://github.com/iotaledger/iota-wiki/issues/1544
- [ ] https://github.com/iotaledger/iota/issues/1438
- [ ] https://github.com/iotaledger/iota/issues/1439
- [ ] https://github.com/iotaledger/iota/issues/1441
- [ ] https://github.com/iotaledger/iota-wiki/issues/1083
- [ ] https://github.com/iotaledger/iota/issues/1435
- [ ] https://github.com/iotaledger/iota-wiki/issues/1546
- [ ] https://github.com/iotaledger/iota/issues/1442
- [ ] https://github.com/iotaledger/iota/issues/1443
- [ ] https://github.com/iotaledger/iota/issues/1436
- [ ] https://github.com/iotaledger/iota-wiki/issues/1548
- [ ] https://github.com/iotaledger/devx/issues/397
- [ ] https://github.com/iotaledger/iota/issues/1444
- [ ] https://github.com/iotaledger/iota/issues/1683
- [ ] https://github.com/iotaledger/devx/issues/498
- [ ] https://github.com/iotaledger/iota/issues/1867
- [ ] https://github.com/iotaledger/iota/issues/2415
- [ ] https://github.com/iotaledger/iota/issues/4096
- [ ] https://github.com/iotaledger/iota/issues/4098
```
