### ISSUE TITLE
[Task (*)]: re-evaluate/re-enable ignored tests

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger/iota#2045]
```[tasklist]
### Tasks
- [ ] `test_traffic_sketch_with_slow_blocks`
- [x] `test_unwind` #3833
- [x] `test_end_to_end` #3833
- [x] bridge related tests (https://github.com/iotaledger/iota/issues/3224)
- [ ] https://github.com/iotaledger/iota/issues/1777
- [ ] https://github.com/iotaledger/iota/issues/3111
- [ ] https://github.com/iotaledger/iota/issues/3899
- [ ] https://github.com/iotaledger/iota/issues/3901
- [ ] https://github.com/iotaledger/iota/issues/3552
- [ ] https://github.com/iotaledger/iota/issues/2983
- [ ] https://github.com/iotaledger/iota/issues/2793
- [ ] https://github.com/iotaledger/iota/issues/3741
- [x] `test_profiler` #3833
- [x] `verify_latest_tx_replay_testnet_mainnet` #3833
- [x] `replay_sandboxes` #3833
- [x] `test_simulated_load_pruning` #3835
- [x] `tombstone_fragmentation` (https://github.com/iotaledger/iota/issues/958)
- [x] `test_checkpoint_executor_cross_epoch` #3835
- [x] `test_reconfig_crash_recovery` #3835
- [x] `access_clock_object_test` #3835
- [x] `test_simulated_load_reconfig_restarts` #3835
- [x] `test_unstaking` (https://github.com/iotaledger/iota/pull/3471)
- [x] `test_timelocked_staking` (https://github.com/iotaledger/iota/pull/2053)
- [x] `test_timelocked_unstaking` (https://github.com/iotaledger/iota/pull/2053)
- [x] 4 x `read_api.rs` tests
- [x] `test_restore_from_disk` (has been removed)
- [x] `test_read_causal_signed_certificates` (has been removed)
- [x] `bullshark_randomised_tests` (has been removed)
- [x] `test_loss_of_liveness_with_recovery` (has been removed)
- [x] `test_loss_of_liveness_without_recovery` (has been removed)
- [x] `test_second_node_restart` (has been removed)
- [x] `test_full_outage_and_recovery` (has been removed)
- [x] `test_node_staggered_starts` (has been removed)
- [x] `test_determinism` (has been removed)
- [x] `display` should stay ignored: "only used to manually check if prints work correctly"
```

**Comment by miker83z** [comment]
Only one left, continues here #4450
