### ISSUE TITLE
[bridge] Report the feasibility of use of the Sui Bridge for IOTA EVM token transfers

### ISSUE THREAD

**Issue by miker83z** [iotaledger/iota#2209]
A brief report should highlight:
- the architecture of Sui Bridge V1
- adoption plan in the current state of the monorepo (configuration needed, supply needed, expected changes to support IOTA EVM)
- critical aspects on the Move side
- critical aspects on the Solidity side
- comparison with the current proposed IOTA-Rebaset-EVM-bridge architecture
```[tasklist]
### Tasks
- [x] Revert the commit that deleted `iota-bridge` and make it compile
- [x] Check upstream changes up to the audited Sui bridge version ~~and pull them~~
- [ ] ~~Test the bridge execution locally~~
- [x] Report the Sui bridge architecture
- [ ] Report Sui Bridge V1 implementation description
- [ ] Report the bridge analysis
```
