### ISSUE TITLE
Add Quizes

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/iota#2579]
Please add the quiz component from the main wiki to the new docs, and use it to add questionnaires for the following documentation sections:

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/iota/issues/2581
- [ ] https://github.com/iotaledger/iota/issues/2582
- [ ] https://github.com/iotaledger/iota/issues/2583
- [ ] https://github.com/iotaledger/iota/issues/2584
- [ ] https://github.com/iotaledger/iota/issues/2585
- [ ] https://github.com/iotaledger/iota/issues/2586
- [ ] https://github.com/iotaledger/iota/issues/2587
- [ ] https://github.com/iotaledger/iota/issues/2588
- [ ] https://github.com/iotaledger/iota/issues/2589
- [ ] https://github.com/iotaledger/iota/issues/2590
- [ ] https://github.com/iotaledger/iota/issues/2591
- [ ] https://github.com/iotaledger/iota/issues/2592
- [ ] https://github.com/iotaledger/iota/issues/2593
```
