### ISSUE TITLE
Integrate dApp Kit

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/iota#2580]
Please integrate the dApp kit into the Getting Started section of the docs so the users can verify they created an account, received funds, and published their first package.

```[tasklist]
### Tasks
- [x] Add dApp kit to Getting Started > Create an Address
- [x] Add dApp kit to Getting Started > Get Test Tokens
- [x] Add dApp kit to Getting Started > Publish a package
```
