### ISSUE TITLE
Facilitate Move adoption by delivering comprehensive, interactive documentation and hosting live sessions

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/iota#3112]
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/iota/issues/3114
- [ ] https://github.com/iotaledger/iota/issues/3115
- [ ] https://github.com/iotaledger/iota/issues/3116
- [ ] https://github.com/iotaledger/iota/issues/2831
- [ ] https://github.com/iotaledger/iota/issues/3117
- [ ] https://github.com/iotaledger/iota/issues/3118
```
