### ISSUE TITLE
Pre-release updates

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/iota#3118]
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/iota/issues/1614
- [ ] https://github.com/iotaledger/iota/issues/3136
- [ ] https://github.com/iotaledger/iota/issues/2990
- [ ] https://github.com/iotaledger/iota/issues/3117
- [ ] https://github.com/iotaledger/iota/issues/3060
- [ ] https://github.com/iotaledger/iota/issues/3137
- [ ] https://github.com/iotaledger/iota/issues/1409
- [ ] https://github.com/iotaledger/iota/issues/3191
- [ ] https://github.com/iotaledger/iota/issues/3230
- [ ] https://github.com/iotaledger/iota/issues/3269
- [ ] https://github.com/iotaledger/iota/issues/1947
- [ ] https://github.com/iotaledger/iota/issues/2880
- [ ] https://github.com/iotaledger/iota/issues/3300
- [ ] https://github.com/iotaledger/iota/issues/3303
- [ ] https://github.com/iotaledger/iota/issues/3389
- [ ] https://github.com/iotaledger/iota/issues/3510
- [ ] https://github.com/iotaledger/iota/issues/3528
- [ ] https://github.com/iotaledger/iota/issues/3800
- [ ] https://github.com/iotaledger/iota/issues/3877
- [ ] https://github.com/iotaledger/iota/issues/3882
- [ ] https://github.com/iotaledger/iota/issues/3883
- [ ] https://github.com/iotaledger/iota/issues/3929
- [ ] https://github.com/iotaledger/iota/issues/3958
- [ ] https://github.com/iotaledger/devx/issues/473
- [ ] https://github.com/iotaledger/iota/issues/4005
- [ ] https://github.com/iotaledger/iota/issues/4106
- [ ] https://github.com/iotaledger/iota/issues/4109
```

**Comment by thibault-martinez** [comment]
Can this be closed?
